export default {
    'Type something': 'إبدأ في الكتابة...',
    // About
    'About Jodit': 'حول جوديت',
    'Jodit Editor': 'محرر جوديت',
    'Free Non-commercial Version': 'الإصدار الغير تجاري مجاني',
    'Jodit User\'s Guide': 'دليل مستخدم جوديت',
    'contains detailed help for using': 'يحتوي على مساعدة مفصلة للاستخدام',
    'For information about the license, please go to our website:': 'للحصول على معلومات حول الترخيص، يرجى الذهاب لموقعنا:',
    'Buy full version': 'شراء النسخة الكاملة',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'حقوق الطبع والنشر © XDSoft.net - Chupurnov Valeriy. كل الحقوق محفوظة.',

    // Toolbar
    'Anchor': 'مِرْساة',
    'Open in new tab': 'فتح في نافذة جديدة',
    'Open editor in fullsize': 'فتح المحرر في الحجم الكامل',
    'Clear Formatting': 'مسح التنسيق',
    'Fill color or set the text color': 'ملء اللون أو تعيين لون النص',
    'Redo': 'إعادة',
    'Undo': 'تراجع',
    'Bold': 'عريض',
    'Italic': 'مائل',
    'Insert Unordered List': 'إدراج قائمة غير مرتبة',
    'Insert Ordered List': 'إدراج قائمة مرتبة',
    'Align Center': 'محاذاة للوسط',
    'Align Justify': 'محاذاة مثبتة',
    'Align Left': 'محاذاة لليسار',
    'Align Right': 'محاذاة لليمين',
    'Insert Horizontal Line': 'إدراج خط أفقي',
    'Insert Image': 'إدراج صورة',
    'Insert youtube/vimeo video': 'إدراج فيديو يوتيوب/فيميو ',
    'Insert link': 'إدراج رابط',
    'Font size': 'حجم الخط',
    'Font family': 'نوع الخط',

    'Insert format block': 'إدراج كتلة تنسيق',
    'Normal': 'عادي',
    'Heading 1': 'عنوان 1',
    'Heading 2': 'عنوان 2',
    'Heading 3': 'عنوان 3',
    'Heading 4': 'عنوان 4',
    'Quote': 'إقتباس',
    'Code': 'كود',

    'Insert': 'إدراج',
    'Insert table': 'إدراج جدول',

    'Decrease Indent': 'تقليل المسافة البادئة',
    'Increase Indent': 'زيادة المسافة البادئة',
    'Select Special Character': 'تحديد أحرف خاصة',
    'Insert Special Character': 'إدراج حرف خاص',

    'Paint format': 'تنسيق الرسم',
    'Change mode': 'تغيير الوضع',

    //plugin Image
    'Margins': 'هوامش',
    'top': 'أعلى',
    'right': 'يمين',
    'bottom': 'أسفل',
    'left': 'يسار',
    'Styles': 'الأنماط',
    'Classes': 'الطبقات',
    'Align': 'محاذاة',
    'Right': 'اليمين',
    'Center': 'الوسط',
    'Left': 'اليسار',
    '--Not Set--': '--غير مضبوط--',
    'Src': 'Src',
    'Title': 'العنوان',
    'Alternative': 'العنوان البديل',
    'Link': 'الرابط',
    'Open link in new tab': 'افتح الرابط في نافذة جديدة',
    'Image': 'الصورة',
    'Advansed': 'متقدم',
    'Image properties': 'خصائص الصورة',
    'Cancel': 'إلغاء',
    'Ok': 'حسنا',

    // File Browser module
    'File Browser': 'متصفح الملفات',
    'Error on load list': 'حدث خطأ في تحميل القائمة ',
    'Error on load folders': 'حدث خطأ في تحميل المجلدات',
    'Are you shure?': 'هل أنت واثق؟',
    'Enter Directory name': 'أدخل اسم المجلد',
    'Create directory': 'إنشاء مجلد',
    'type name': 'أكتب إسم',

    // Form module
    'Drop image': 'إسقاط صورة',
    'or click': 'أو أنقر',
    'Alternative text': 'النص البديل',
    'Upload': 'رفع',
    'Browse': 'تصفح',
    'Background': 'الخلفية',
    'Text': 'نص',

    // popap module
    'Top': 'أعلى',
    'Middle': 'الوسط',
    'Bottom': 'الأسفل',
    'Insert column before': 'إدراج عمود قبل',
    'Insert column after': 'إدراج عمود بعد',
    'Insert row above': 'إدراج صف أعلى',
    'Insert row below': 'إدراج صف أسفل',
    'Delete table': 'حذف الجدول',
    'Delete row': 'حذف الصف',
    'Delete column': 'حذف العمود',
    'Empty cell': 'خلية فارغة'
};
