/*!
 * Jodit Editor (https://xdsoft.net/jodit/)
 * Released under MIT see LICENSE.txt in the project root for license information.
 * Copyright (c) 2013-2026 Valerii Chupurnov. All rights reserved. https://xdsoft.net
 */

// Azerbaijani

module.exports = {
	'Type something': 'Mətn daxil edin',
	Advanced: 'Ətraflı',
	'About Jodit': 'Jodit haqqında',
	'Jodit Editor': 'Jodit Redaktoru',
	"Jodit User's Guide": 'Jodit istifadəçi bələdçisi',
	'contains detailed help for using':
		'istifadə üzrə ətraflı kömək məlumatını əhatə edir',
	'For information about the license, please go to our website:':
		'Lisenziya haqqında məlumat üçün veb saytımıza daxil olun:',
	'Buy full version': 'Tam versiyanı satın al',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Copyright © XDSoft.net - Chupurnov Valeriy. Bütün hüquqlar qorunur.',
	Anchor: 'Lövbər',
	'Open in new tab': 'Yeni vərəqdə aç',
	'Open in fullsize': 'Tam ölçüdə aç',
	'Clear Formatting': 'Formatlamanı təmizlə',
	'Fill color or set the text color':
		'Doldurma rəngini və ya mətn rəngini təyin et',
	Redo: 'Təkrarla',
	Undo: 'Geri qaytar',
	Bold: 'Qalın',
	Italic: 'Kursiv',
	'Insert Unordered List': 'Nizamsız siyahı əlavə et',
	'Insert Ordered List': 'Nömrələnmiş siyahı əlavə et',
	'Align Center': 'Ortaya düzləndir',
	'Align Justify': 'Enə görə düzləndir',
	'Align Left': 'Sola düzləndir',
	'Align Right': 'Sağa düzləndir',
	'Insert Horizontal Line': 'Üfüqi xətt əlavə et',
	'Insert Image': 'Şəkil əlavə et',
	'Insert file': 'Fayl əlavə et',
	'Insert youtube/vimeo video': 'Youtube/vimeo video əlavə et',
	'Insert link': 'Keçid əlavə et',
	'Font size': 'Şrift ölçüsü',
	'Font family': 'Şrift ailəsi',
	'Line height': 'Sətir hündürlüyü',
	Spellcheck: 'Orfoqrafiya yoxlaması',
	'Speech Recognize': 'Nitqin tanınması',
	newline: 'Yeni sətir',
	'Insert format block': 'Format bloku əlavə et',
	Normal: 'Normal',
	'Heading 1': 'Başlıq 1',
	'Heading 2': 'Başlıq 2',
	'Heading 3': 'Başlıq 3',
	'Heading 4': 'Başlıq 4',
	Quote: 'Sitat',
	Code: 'Kod',
	Insert: 'Əlavə et',
	'Insert table': 'Cədvəl əlavə et',
	'Decrease Indent': 'Girintini azalt',
	'Increase Indent': 'Girintini artır',
	'Select Special Character': 'Xüsusi simvol seç',
	'Insert Special Character': 'Xüsusi simvol əlavə et',
	'Paint format': 'Format fırçası',
	'Change mode': 'Rejimi dəyiş',
	Margins: 'Kənar boşluqlar',
	top: 'Yuxarı',
	right: 'Sağ',
	bottom: 'Aşağı',
	left: 'Sol',
	Styles: 'Üslublar',
	Classes: 'CSS Klasları',
	Align: 'Düzləndirmə',
	Right: 'Sağ',
	Center: 'Mərkəz',
	Left: 'Sol',
	'--Not Set--': '--Təyin edilməyib--',
	Src: 'Mənbə',
	Title: 'Başlıq',
	Alternative: 'Alternativ mətn',
	Link: 'Keçid',
	'Open link in new tab': 'Keçidi yeni vərəqdə aç',
	Image: 'Şəkil',
	file: 'Fayl',
	'Image properties': 'Şəkil xassələri',
	Cancel: 'Ləğv et',
	Ok: 'OK',
	'Your code is similar to HTML. Keep as HTML?':
		'Kodunuz HTML-ə bənzəyir. HTML kimi saxlanılsın?',
	'Paste as HTML': 'HTML kimi yerləşdir',
	Keep: 'Saxla',
	Clean: 'Təmizlə',
	'Insert as Text': 'Mətn kimi əlavə et',
	'Word Paste Detected': 'Word-dən yapışdırma aşkarlandı',
	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'Yerləşdirdiyiniz məzmun Microsoft Word/Excel sənədindəndir. Formatı saxlamaq, yoxsa təmizləmək istəyirsiniz?',
	'Insert only Text': 'Yalnız mətni əlavə et',
	'File Browser': 'Fayl brauzeri',
	'Error on load list': 'Siyahının yüklənməsində xəta',
	'Error on load folders': 'Qovluqların yüklənməsində xəta',
	'Are you sure?': 'Əminsiniz?',
	'Enter Directory name': 'Qovluq adını daxil edin',
	'Create directory': 'Qovluq yarat',
	'type name': 'adı yazın',
	'type dir name': 'qovluq adını yazın',
	'Drop image': 'Şəkli buraya buraxın',
	'Drop file': 'Faylı buraya buraxın',
	'or click': 'və ya buraya klikləyin',
	'Alternative text': 'Alternativ mətn',
	Browse: 'Seç',
	Upload: 'Yüklə',
	Background: 'Arxa fon',
	Text: 'Mətn',
	Top: 'Yuxarı',
	Middle: 'Orta',
	Bottom: 'Aşağı',
	'Insert column before': 'Əvvəlinə sütun əlavə et',
	'Insert column after': 'Sonrasına sütun əlavə et',
	'Insert row above': 'Yuxarıya sətir əlavə et',
	'Insert row below': 'Aşağıya sətir əlavə et',
	'Delete table': 'Cədvəli sil',
	'Delete row': 'Sətri sil',
	'Delete column': 'Sütunu sil',
	'Empty cell': 'Xananı boşalt',
	Delete: 'Sil',
	'Strike through': 'Üstündən xətt çək',
	Underline: 'Altından xətt çək',
	Break: 'Fasilə',
	'Search for': 'Axtar',
	'Replace with': 'Bununla əvəz et',
	Replace: 'Əvəz et',
	Edit: 'Redaktə et',
	'Vertical align': 'Şaquli düzləndirmə',
	'Horizontal align': 'Üfüqi düzləndirmə',
	Filter: 'Süzgəc',
	'Sort by changed': 'Dəyişməyə görə sırala',
	'Sort by name': 'Ada görə sırala',
	'Sort by size': 'Ölçüyə görə sırala',
	'Add folder': 'Qovluq əlavə et',
	'Split vertical': 'Şaquli böl',
	'Split horizontal': 'Üfüqi böl',
	Split: 'Böl',
	Merge: 'Birləşdir',
	'Add column': 'Sütun əlavə et',
	'Add row': 'Sətir əlavə et',
	Border: 'Haşiyə',
	'Embed code': 'Kodu daxil et',
	Update: 'Yenilə',
	superscript: 'Yuxarı indeks',
	subscript: 'Aşağı indeks',
	'Cut selection': 'Seçimi kəs',
	Paste: 'Yerləşdir',
	'Choose Content to Paste': 'Yerləşdiriləcək məzmunu seçin',
	'Chars: %d': 'Simvol: %d',
	'Words: %d': 'Söz: %d',
	All: 'Hamısını seç',
	'Select %s': 'Seç: %s',
	'Select all': 'Hamısını seç',
	source: 'HTML',
	bold: 'Qalın',
	italic: 'Kursiv',
	brush: 'Fırça',
	link: 'Keçid',
	undo: 'Geri qaytar',
	redo: 'Təkrarla',
	table: 'Cədvəl',
	image: 'Şəkil',
	eraser: 'Silgi',
	paragraph: 'Abzas',
	fontsize: 'Şrift ölçüsü',
	video: 'Video',
	font: 'Şrift',
	about: 'Haqqında',
	print: 'Çap et',
	underline: 'Altından xətt çək',
	strikethrough: 'Üstündən xətt çək',
	indent: 'Girinti',
	outdent: 'Çıxıntı',
	fullsize: 'Tam ölçü',
	shrink: 'Kiçilt',
	hr: 'Xətt',
	ul: 'Nizamsız siyahı',
	ol: 'Nömrələnmiş siyahı',
	'Lower Alpha': 'Kiçik hərflər',
	'Upper Alpha': 'Böyük hərflər',
	'Lower Roman': 'Kiçik Roma rəqəmləri',
	'Upper Roman': 'Böyük Roma rəqəmləri',
	'Lower Greek': 'Yunan hərfləri',
	cut: 'Kəs',
	selectall: 'Hamısını seç',
	'Open link': 'Keçidi aç',
	'Edit link': 'Keçidi redaktə et',
	'No follow': 'Nofollow atributu',
	Unlink: 'Keçidi ləğv et',
	Eye: 'Bax',
	pencil: 'Redaktə et',
	' URL': 'URL',
	Reset: 'Sıfırla',
	Save: 'Yadda saxla',
	'Save as ...': 'Fərqli yadda saxla...',
	Resize: 'Ölçüsünü dəyiş',
	Crop: 'Kəs',
	Width: 'En',
	Height: 'Hündürlük',
	'Keep Aspect Ratio': 'Nisbəti saxla',
	Yes: 'Bəli',
	No: 'Xeyr',
	Remove: 'Çıxar',
	Select: 'Seç',
	'You can only edit your own images. Download this image on the host?':
		'Siz yalnız öz şəkillərinizi redaktə edə bilərsiniz. Bu şəkil serverə yüklənsin?',
	'The image has been successfully uploaded to the host!':
		'Şəkil serverə uğurla yükləndi!',
	palette: 'Palitra',
	'There are no files': 'Bu qovluqda fayl yoxdur.',
	Rename: 'Adını dəyiş',
	'Enter new name': 'Yeni ad daxil edin',
	preview: 'Önbaxış',
	download: 'Endir',
	'Paste from clipboard': 'Mübadilə buferindən yerləşdir',
	"Your browser doesn't support direct access to the clipboard.":
		'Brauzeriniz mübadilə buferinə birbaşa girişi dəstəkləmir.',
	'Copy selection': 'Seçimi kopyala',
	copy: 'Kopyala',
	'Border radius': 'Haşiyə radiusu',
	'Show all': 'Hamısını göstər',
	Apply: 'Tətbiq et',
	'Please fill out this field': 'Zəhmət olmasa bu xananı doldurun',
	'Please enter a web address': 'Zəhmət olmasa veb ünvan daxil edin',
	Default: 'Standart',
	Circle: 'Dairə',
	Dot: 'Nöqtə',
	Quadrate: 'Kvadrat',
	Find: 'Tap',
	'Find Previous': 'Əvvəlkini tap',
	'Find Next': 'Növbətini tap',
	'Insert className': 'className (CSS) əlavə et',
	'Press Alt for custom resizing':
		'Fərdi ölçüləndirmə üçün Alt düyməsini basın',
	'License: %s': 'Lisenziya: %s'
};
