import Jodit from '../Jodit'
export default Jodit.lang.de = {
    'Type something': 'Schreibe etwas',
    // About
    'About Jodit': 'Über Jodi',
    'Jodit Editor': 'Jodit Editor',
    'Free Non-commercial Version': 'Freie Nicht-kommerzielle Version',
    'Jodit User\'s Guide': 'Jodit Benutzerhandbuch',
    'contains detailed help for using': 'ausführliche Hilfe enthält für die Verwendung von',
    'For information about the license, please go to our website:': 'Für Informationen über die Lizenz, gehen Sie bitte auf unsere Webseite:',
    'Buy full version': 'Vollversion kaufen',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'Copyright © XDSoft.net - Chupurnov Valeriy. Alle Rechte vorbehalten.',
    
    // Toolbar
    'Anchor': 'Anker',
    'Open in new tab': 'In neuer Registerkarte öffnen',
    'Open editor in fullsize': 'Editor öffnen in voller Größe',
    'Clear Formatting': 'Formatierung löschen',
    'Fill color or set the text color': 'Füllen Sie Farbe oder stellen Sie die Textfarbe',
    'Redo': 'Redo',
    'Undo': 'Rückgängig machen',
    'Bold': 'Fett gedruckt',
    'Italic': 'Kursiv',
    'Insert Unordered List': 'Ungeordnete Liste einfügen',
    'Insert Ordered List': 'Legen Sie Sortierte Liste',
    'Justify Center': 'einmitten',
    'Justify Full': 'Begründen Voll',
    'Justify Left': 'Begründen links',
    'Justify Right': 'Begründen Rechts',
    'Insert Horizontal Line': 'Legen Horizontale Linie',
    'Insert Image': 'Bild einfügen',
    'Insert link': 'Link einfügen',
    'Font size': 'Schriftgröße',
    'Font family': 'Schriftfamilie',

    'Insert format block': 'Insert Format Block',
    'Normal': 'Normal',
    'Heading 1': 'Überschrift 1',
    'Heading 2': 'Überschrift 2',
    'Heading 3': 'Überschrift 3',
    'Heading 4': 'Überschrift 4',
    'Quote': 'Zitat',
    'Code': 'Code',

    'Insert': 'Einfügen',
    'Insert table': 'Tabelle einfügen',
    'Change mode': 'Änderungsmodus',
    
    //plugin Image
    'Margins': 'Die Margen',
    'top': 'oben',
    'right': 'Recht',
    'bottom': 'Boden',
    'left': 'links',
    'Styles': 'Styles',
    'Classes': 'Klassen',
    'Align': 'Ausrichten',
    'Right': 'Recht',
    'Center': 'Center',
    'Left': 'Links',
    '--Not Set--': '--Nicht eingestellt--',
    'Src': 'src',
    'Title': 'Titel',
    'Alternative': 'Alternative (alt)',
    'Link': 'Link',
    'Open link in new tab': 'Link in neuem Tab öffnen',
    'Image': 'Image',
    'Advansed': 'Erweiterte',
    'Image properties': 'Bildeigenschaften',
    'Cancel': 'Stornieren',
    'Ok': 'OK',
    
    // File Browser module
    'File Browser': 'Dateibrowser',
    'Error on load list': 'Fehler beim Ladeliste',
    'Error on load folders': 'Fehler beim Laden Ordner',
    'Are you shure?': 'Bist du sicher?',
    'Enter Directory name': 'Geben Sie Verzeichnisname',
    'Create directory': 'Verzeichnis erstellen',
    'type name': 'Modellname',
    
    // Form module
    'Drop image': 'Bild Tropfen',
    'or click': 'oder klicken Sie auf',
    'Alternative text': 'Alternativer Text',
    'Browse': 'Blättern',
    'Upload': 'Hochladen',

    'Background': 'Hintergrund',
    'Text': 'Text',
    
     // popap module
    'Top': 'Oben',
    'Middle': 'Mitte',
    'Bottom': 'Boden',
    'Insert column before': 'Spalte einfügen vor',
    'Insert column after': 'Spalte einfügen nach',
    'Insert row above': 'Zeile einfügen oben',
    'Insert row below': 'Zeile unterhalb einfügen',
    'Delete table': 'Tabelle löschen',
    'Delete row': 'Zeile löschen',
    'Delete column': 'Spalte löschen',
    'Empty cell': 'Leere Zelle'
};