export default {
    'Type something': 'Start writing...',
    // About
    'About Jodit': '',
    'Jodit Editor': '',
    'Free Non-commercial Version': '',
    'Jodit User\'s Guide': '',
    'contains detailed help for using': '',
    'For information about the license, please go to our website:': '',
    'Buy full version': '',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': '',
    
    // Toolbar
    'Anchor': '',
    'Open in new tab': '',
    'Open editor in fullsize': '',
    'Clear Formatting': '',
    'Fill color or set the text color': '',
    'Redo': '',
    'Undo': '',
    'Bold': '',
    'Italic': '',
    'Insert Unordered List': '',
    'Insert Ordered List': '',
    'Align Center': '',
    'Align Justify': '',
    'Align Left': '',
    'Align Right': '',
    'Insert Horizontal Line': '',
    'Insert Image': '',
    'Insert youtube/vimeo video': '',
    'Insert link': '',
    'Font size': '',
    'Font family': '',

    'Insert format block': '',
    'Normal': '',
    'Heading 1': '',
    'Heading 2': '',
    'Heading 3': '',
    'Heading 4': '',
    'Quote': '',
    'Code': '',

    'Insert': '',
    'Insert table': '',

    'Paint format': '',
    'Change mode': '',
    
    //plugin Image
    'Margins': '',
    'top': '',
    'right': '',
    'bottom': '',
    'left': '',
    'Styles': '',
    'Classes': '',
    'Align': '',
    'Right': '',
    'Center': '',
    'Left': '',
    '--Not Set--': '',
    'Src': '',
    'Title': '',
    'Alternative': '',
    'Link': '',
    'Open link in new tab': '',
    'Image': '',
    'Advansed': '',
    'Image properties': '',
    'Cancel': '',
    'Ok': '',
    
    // File Browser module
    'File Browser': '',
    'Error on load list': '',
    'Error on load folders': '',
    'Are you shure?': '',
    'Enter Directory name': '',
    'Create directory': '',
    'type name': '',
    
    // Form module
    'Drop image': '',
    'or click': '',
    'Alternative text': '',
    'Upload': '',
    'Browse': '',
    'Background': '',
    'Text': '',
    
    // popap module
    'Top': '',
    'Middle': '',
    'Bottom': '',
    'Insert column before': '',
    'Insert column after': '',
    'Insert row above': '',
    'Insert row below': '',
    'Delete table': '',
    'Delete row': '',
    'Delete column': '',
    'Empty cell': ''
};
