export default {
    'Type something': 'Ecrivez ici',
    // About
    'About Jodit': 'A propos de Jodit',
    'Jodit Editor': 'Editeur Jodit',
    'Free Non-commercial Version': 'Version gratuite, non commerciale',
    'Jodit User\'s Guide': 'Guide de l\'utilisateur',
    'contains detailed help for using': 'Aide détaillée à l\'utilisation',
    'For information about the license, please go to our website:': 'Consulter la licence sur notre site web:',
    'Buy full version': 'Acheter la version complète',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'Copyright © XDSoft.net - Chupurnov Valeriy. Tous droits réservés.',
    
    // Toolbar
    'Anchor': 'Ancre',
    'Open in new tab': 'Ouvrir dans un nouvel onglet',
    'Open editor in fullsize': 'Ouvrir l\'éditeur en pleine page',
    'Clear Formatting': 'Supprimer le formattage',
    'Fill color or set the text color': 'Modifier la couleur du fond ou du texte',
    'Redo': 'Refaire',
    'Undo': 'Défaire',
    'Bold': 'Gras',
    'Italic': 'Italique',
    'Insert Unordered List': 'Liste non ordonnée',
    'Insert Ordered List': 'Liste ordonnée',
    'Align Center': 'Centrer',
    'Align Justify': 'Justifier',
    'Align Left': 'Aligner à gauche ',
    'Align Right': 'Aligner à droite',
    'Insert Horizontal Line': 'Insérer une ligne horizontale',
    'Insert Image': 'Insérer une image',
    'Insert youtube/vimeo video': 'Insérer une vidéo',
    'Insert link': 'Insérer un lien',
    'Font size': 'Taille des caractères',
    'Font family': 'Famille des caractères',

    'Insert format block': 'Bloc formatté',
    'Normal': 'Normal',
    'Heading 1': 'Titre 1',
    'Heading 2': 'Titre 2',
    'Heading 3': 'Titre 3',
    'Heading 4': 'Titre 4',
    'Quote': 'Citation',
    'Code': 'Code',

    'Insert': 'Insérer',
    'Insert table': 'Insérer un tableau',

    'Decrease Indent': 'Diminuer le retrait',
    'Increase Indent': 'Retrait plus',
    'Select Special Character': 'Sélectionnez un caractère spécial',
    'Insert Special Character': 'Insérer un caractère spécial',

    'Paint format': 'Cloner le format',
    'Change mode': 'Mode wysiwyg <-> code html',

    //plugin Image
    'Margins': 'Marges',
    'top': 'haut',
    'right': 'droite',
    'bottom': 'Bas',
    'left': 'gauche',
    'Styles': 'Styles',
    'Classes': 'Classes',
    'Align': 'Alignement',
    'Right': 'Droite',
    'Center': 'Centre',
    'Left': 'Gauche',
    '--Not Set--': '--Non disponible--',
    'Src': 'Source',
    'Title': 'Titre',
    'Alternative': 'Alternative',
    'Link': 'Lien',
    'Open link in new tab': 'Ouvrir le lien dans un nouvel onglet',
    'Image': 'Image',
    'Advansed': 'Avancé',
    'Image properties': 'Propriétés de l\'image',
    'Cancel': 'Effacer',
    'Ok': 'OK',
    
    // File Browser module
    'File Browser': 'Explorateur de fichiers',
    'Error on load list': 'Erreur de liste de chargement',
    'Error on load folders': 'Erreur de dossier de chargement',
    'Are you shure?': 'Etes-vous sûrs ?',
    'Enter Directory name': 'Entrer le non de dossier',
    'Create directory': 'Créer un dossier',
    'type name': 'type de fichier',
    
    // Form module
    'Drop image': 'Coller une image',
    'or click': 'ou cliquer',
    'Alternative text': 'Texte de remplacemement',
    'Browse': 'Chercher',
    'Upload': 'Charger',
    'Background': 'Arrière-plan',
    'Text': 'Texte',
    
    // popap module
    'Top': 'Haut',
    'Middle': 'Milieu',
    'Bottom': 'Bas',
    'Insert column before': 'Insérer une colonne avant',
    'Insert column after': 'Insérer une colonne après',
    'Insert row above': 'Insérer une ligne en dessus',
    'Insert row below': 'Insérer une ligne en dessous',
    'Delete table': 'Supprimer le tableau',
    'Delete row': 'Supprimer la ligne',
    'Delete column': 'Supprimer la colonne',
    'Empty cell': 'Vider la cellule'
    }
