import { IDictionary } from '../types';

export default {
	'Type something': 'なにかタイプしてください',
	// About
	Advanced: 'Advanced',
	'About Jodit': 'Joditについて',
	'Jodit Editor': 'Jodit Editor',
	'Free Non-commercial Version': 'Free Non-commercial Version',
	'GNU General Public License, version 2 or later':
		'GNU General Public License, version 2 or later',
	"Jodit User's Guide": "Jodit ユーザーズ・ガイド",
	'contains detailed help for using': '詳しい使い方',
	'For information about the license, please go to our website:':
		'ライセンス詳細についてはJodit Webサイトを確認ください：',
	'Buy full version': 'フルバージョンを購入',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Copyright © XDSoft.net - Chupurnov Valeriy.' + ' All rights reserved.',

	// Toolbar
	Anchor: 'Anchor',
	'Open in new tab': '新しいタブで開く',
	'Open editor in fullsize': 'フルサイズでエディターを開く',
	'Clear Formatting': '書式をクリア',
	'Fill color or set the text color': '文字の色',
	Redo: 'やり直し',
	Undo: '元に戻す',
	Bold: '太字',
	Italic: '斜体',
	'Insert Unordered List': '箇条書き',
	'Insert Ordered List': '番号付きリスト',
	'Align Center': '中央揃え',
	'Align Justify': '両端揃え',
	'Align Left': '左揃え',
	'Align Right': '右揃え',
	'Insert Horizontal Line': '区切り線を挿入',
	'Insert Image': '画像を挿入',
	'Insert file': 'ファイルを挿入',
	'Insert youtube/vimeo video': 'youtube/vimeo 動画',
	'Insert link': 'リンクを挿入',
	'Font size': 'フォントサイズ',
	'Font family': 'フォント',

	'Insert format block': 'Insert format block',
	Normal: '文本',
	'Heading 1': '見出し 1',
	'Heading 2': '見出し 2',
	'Heading 3': '見出し 3',
	'Heading 4': '見出し 4',
	Quote: '引用',
	Code: 'コード',

	Insert: '挿入',
	'Insert table': '表を挿入',

	'Decrease Indent': 'インデント減',
	'Increase Indent': 'インデント増',
	'Select Special Character': '特殊文字を選択',
	'Insert Special Character': '特殊文字を挿入',

	'Paint format': '書式を貼付け',
	'Change mode': 'モード変更',

	// plugin Image
	Margins: 'マージン',
	top: '上',
	right: '右',
	bottom: '下',
	left: '左',
	Styles: 'スタイル',
	Classes: 'クラス',
	Align: '配置',
	Right: '右寄せ',
	Center: '中央寄せ',
	Left: '左寄せ',
	'--Not Set--': '無',
	Src: 'ソース',
	Title: 'タイトル',
	Alternative: '代替テキスト',
	Link: 'リンク',
	'Open link in new tab': '新しいタブで開く',
	Image: '画像',
	file: 'ファイル',
	Advansed: 'Advansed',
	'Image properties': '画像のプロパティー',
	Cancel: 'キャンセル',
	Ok: '確定',

	// plugin paste
	'Your code is similar to HTML. Keep as HTML?':
		'HTMLコードを保持しますか？',
	'Paste as HTML': 'HTMLで貼付け',
	Keep: '保留源格式',
	Clean: '匹配目標格式',
	'Insert as Text': '把html代碼視為普通文本',
	'Word Paste Detected': '文本黏貼',

	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'正在黏貼 Word/Excel 的文本，是否保留源格式？',

	'Insert only Text': '只保留文本',

	// File Browser module
	'File Browser': '文件管理',
	'Error on load list': '加載list錯誤',
	'Error on load folders': '加載folders錯誤',
	'Are you sure?': '你確定嗎？',
	'Enter Directory name': '輸入路徑',
	'Create directory': '創建路徑',
	'type name': 'type name',

	// Form module
	'Drop image': '拖動圖片到此',
	'Drop file': '拖動文件到此',
	'or click': '或點擊',
	'Alternative text': 'Alternative text',
	Browse: 'ブラウズ',
	Upload: 'アップロード',
	Background: '背景色',
	Text: '文字',

	// popap module
	Top: '頂部',
	Middle: '中間',
	Bottom: '底部',
	'Insert column before': '在之前插入列',
	'Insert column after': '在之後插入列',
	'Insert row above': '在之前插入行',
	'Insert row below': '在之後插入行',
	'Delete table': '刪除表格',
	'Delete row': '刪除行',
	'Delete column': '刪除列',
	'Empty cell': '清除內容',

	// stat
	'Chars: %d': '文字数: %d',
	'Words: %d': '単語数: %d',

	'Strike through': '刪除線',
	Underline: '下劃線',
	superscript: '上標',
	subscript: '下標',
	'Cut selection': '剪切',
	'Select all': '全選',
	Break: 'Pause',
	'Search for': '查找',
	'Replace with': '替換為',
	Replace: '替換',
	Paste: '黏貼',
	'Choose Content to Paste': '選擇內容並黏貼',

	All: '全部',
	source: '源碼',
	bold: '粗體',
	italic: '斜體',
	brush: '顏色',
	link: '鏈接',
	undo: '撤銷',
	redo: '重做',
	table: '表格',
	image: '圖片',
	eraser: '橡皮擦',
	paragraph: '段落',
	fontsize: '字號',
	video: '影片',
	font: '字體',
	about: '關於',
	print: '打印',
	symbol: '符號',
	underline: '下劃線',
	strikethrough: '上出現',
	indent: '增加縮進',
	outdent: '減少縮進',
	fullsize: '全屏',
	shrink: '收縮',
	copyformat: '複製格式',
	hr: '分割線',
	ul: '無序列表',
	ol: '順序列表',
	cut: '剪切',
	selectall: '全選',
	'Open link': '打開鏈接',
	'Edit link': '編輯鏈接',
	'No follow': 'No follow',
	Unlink: 'Unlink',
	Eye: '回顧',
	' URL': 'URL',
	Reset: '重置',
	Save: '保存',
	'Save as ...': '保存為',
	Resize: '調整大小',
	Crop: 'Crop',
	Width: '寬',
	Height: '高',
	'Keep Aspect Ratio': '保存長寬比',
	Yes: 'はい',
	No: 'いいえ',
	Remove: '移除',
	Select: '選択',
	'Select %s': '選択: %s',
	Update: '更新',
	'Vertical align': '垂直對齊',
	Merge: '合併',
	'Add column': '添加列',
	'Add row': '添加行',
	Border: '邊框',
	'Embed code': '嵌入代碼',
	Delete: '刪除',
	'Horizontal align': '水平對齊',

	Filter: '篩選',
	'Sort by changed': '修改時間排序',
	'Sort by name': '名稱排序',
	'Sort by size': '大小排序',
	'Add folder': '新建文件夾',
	Split: '拆分',
	'Split vertical': '垂直拆分',
	'Split horizontal': '水平拆分',
	'You can only edit your own images. Download this image on the host?':
		'妳只能編輯妳自己的圖片。' + 'Download this image on the host?',
	'The image has been successfully uploaded to the host!': '圖片上傳成功',
	palette: 'パレット',
	pencil: '鉛筆',
	'There are no files': '此目錄中沒有文件。',
	rename: '重命名',
	'Enter new name': '輸入新名稱',
	preview: 'プレビュー',
	download: 'ダウンロード',
	'Paste from clipboard': 'クリップボードから貼付け',
	'Your browser doesn\'t support direct access to the clipboard.': 'お使いのブラウザはクリップボードを使用できません',
	'Copy selection': 'Copy selection',
	'copy': 'copy',
	'Border radius': 'Border radius',
} as IDictionary<string>;
