import { IDictionary } from '../types';

export default {
	'Type something': 'なにかタイプしてください',
	// About
	Advanced: '高度な設定',
	'About Jodit': 'Joditについて',
	'Jodit Editor': 'Jodit Editor',
	'Free Non-commercial Version': 'Free Non-commercial Version',
	'GNU General Public License, version 2 or later':
		'GNU General Public License, version 2 or later',
	"Jodit User's Guide": "Jodit ユーザーズ・ガイド",
	'contains detailed help for using': '詳しい使い方',
	'For information about the license, please go to our website:':
		'ライセンス詳細についてはJodit Webサイトを確認ください：',
	'Buy full version': 'フルバージョンを購入',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Copyright © XDSoft.net - Chupurnov Valeriy.' + ' All rights reserved.',

	// Toolbar
	Anchor: 'Anchor',
	'Open in new tab': '新しいタブで開く',
	'Open editor in fullsize': 'エディターのサイズ（フル/ノーマル）',
	'Clear Formatting': '書式をクリア',
	'Fill color or set the text color': 'テキストの色',
	Redo: 'やり直し',
	Undo: '元に戻す',
	Bold: '太字',
	Italic: '斜体',
	'Insert Unordered List': '箇条書き',
	'Insert Ordered List': '番号付きリスト',
	'Align Center': '中央揃え',
	'Align Justify': '両端揃え',
	'Align Left': '左揃え',
	'Align Right': '右揃え',
	'Insert Horizontal Line': '区切り線を挿入',
	'Insert Image': '画像を挿入',
	'Insert file': 'ファイルを挿入',
	'Insert youtube/vimeo video': 'Youtube/Vimeo 動画',
	'Insert link': 'リンクを挿入',
	'Font size': 'フォントサイズ',
	'Font family': 'フォント',

	'Insert format block': 'テキストのスタイル',
	Normal: '指定なし',
	'Heading 1': 'タイトル1',
	'Heading 2': 'タイトル2',
	'Heading 3': 'タイトル3',
	'Heading 4': 'タイトル4',
	Quote: '引用',
	Code: 'コード',

	Insert: '挿入',
	'Insert table': '表を挿入',

	'Decrease Indent': 'インデント減',
	'Increase Indent': 'インデント増',
	'Select Special Character': '特殊文字を選択',
	'Insert Special Character': '特殊文字を挿入',

	'Paint format': '書式を貼付け',
	'Change mode': '編集モード切替え',

	// plugin Image
	Margins: 'マージン',
	top: '上',
	right: '右',
	bottom: '下',
	left: '左',
	Styles: 'スタイル',
	Classes: 'クラス',
	Align: '配置',
	Right: '右寄せ',
	Center: '中央寄せ',
	Left: '左寄せ',
	'--Not Set--': '指定なし',
	Src: 'ソース',
	Title: 'タイトル',
	Alternative: '代替テキスト',
	Link: 'リンク',
	'Open link in new tab': '新しいタブで開く',
	Image: '画像',
	file: 'ファイル',
	Advansed: 'Advansed',
	'Image properties': '画像のプロパティー',
	Cancel: 'キャンセル',
	Ok: '確定',

	// plugin paste
	'Your code is similar to HTML. Keep as HTML?':
		'HTMLコードを保持しますか？',
	'Paste as HTML': 'HTMLで貼付け',
	Keep: '保留源格式',
	Clean: '匹配目標格式',
	'Insert as Text': '把html代碼視為普通文本',
	'Word Paste Detected': '文本黏貼',

	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'正在黏貼 Word/Excel 的文本，是否保留源格式？',

	'Insert only Text': '只保留文本',

	// File Browser module
	'File Browser': '文件管理',
	'Error on load list': '加載list錯誤',
	'Error on load folders': '加載folders錯誤',
	'Are you sure?': '你確定嗎？',
	'Enter Directory name': '輸入路徑',
	'Create directory': '創建路徑',
	'type name': 'type name',

	// Form module
	'Drop image': 'ここに画像をドロップ',
	'Drop file': 'ここにファイルをドロップ',
	'or click': 'or クリック',
	'Alternative text': '代替テキスト',
	Browse: 'ブラウズ',
	Upload: 'アップロード',
	Background: '背景',
	Text: '文字',

	// popap module
	Top: '上',
	Middle: '中央',
	Bottom: '下',
	'Insert column before': '左に列を挿入',
	'Insert column after': '右に列を挿入',
	'Insert row above': '上に行を挿入',
	'Insert row below': '下に行を挿入',
	'Delete table': '表を削除',
	'Delete row': '行を削除',
	'Delete column': '列を削除',
	'Empty cell': 'セルを空にする',

	// stat
	'Chars: %d': '文字数: %d',
	'Words: %d': '単語数: %d',

	'Strike through': '取り消し線',
	Underline: '下線',
	superscript: '上付き文字',
	subscript: '下付き文字',
	'Cut selection': '切り取り',
	'Select all': 'すべて選択',
	Break: 'Pause',
	'Search for': '検索',
	'Replace with': '置換',
	Replace: '置換',
	Paste: '貼付け」',
	'Choose Content to Paste': '選択した内容を貼付け',

	All: '全部',
	source: '源碼',
	bold: '粗體',
	italic: '斜體',
	brush: '顏色',
	link: '鏈接',
	undo: '撤銷',
	redo: '重做',
	table: '表格',
	image: '圖片',
	eraser: '橡皮擦',
	paragraph: '段落',
	fontsize: '字號',
	video: '影片',
	font: '字體',
	about: '關於',
	print: '打印',
	symbol: '符號',
	underline: '下劃線',
	strikethrough: '上出現',
	indent: '增加縮進',
	outdent: '減少縮進',
	fullsize: '全屏',
	shrink: '收縮',
	copyformat: '複製格式',
	hr: '分割線',
	ul: '箇条書き',
	ol: '番号付きリスト',
	cut: '切り取り',
	selectall: 'すべて選択',
	'Open link': 'リンクを開く',
	'Edit link': 'リンクを編集',
	'No follow': 'No follow',
	Unlink: 'リンク解除',
	Eye: 'サイトを確認',
	' URL': 'URL',
	Reset: 'リセット',
	Save: '保存',
	'Save as ...': '保存為',
	Resize: 'リサイズ',
	Crop: 'Crop',
	Width: '幅',
	Height: '高さ',
	'Keep Aspect Ratio': '縦横比を保持',
	Yes: 'はい',
	No: 'いいえ',
	Remove: '移除',
	Select: '選択',
	'Select %s': '選択: %s',
	Update: '更新',
	'Vertical align': '垂直方向の配置',
	Merge: 'セルの結合',
	'Add column': '列を追加',
	'Add row': '行を追加',
	Border: '境界線',
	'Embed code': '埋め込みコード',
	Delete: '削除',
	Edit: '編集',
	'Horizontal align': '水平方向の配置',

	Filter: '篩選',
	'Sort by changed': '修改時間排序',
	'Sort by name': '名稱排序',
	'Sort by size': '大小排序',
	'Add folder': '新建文件夾',
	Split: '分割',
	'Split vertical': 'セルの分割（垂直方向）',
	'Split horizontal': 'セルの分割（水平方向）',
	'You can only edit your own images. Download this image on the host?':
		'妳只能編輯妳自己的圖片。' + 'Download this image on the host?',
	'The image has been successfully uploaded to the host!': '圖片上傳成功',
	palette: 'パレット',
	pencil: '鉛筆',
	'There are no files': '此目錄中沒有文件。',
	rename: '重命名',
	'Enter new name': '輸入新名稱',
	preview: 'プレビュー',
	download: 'ダウンロード',
	'Paste from clipboard': '貼り付け',
	'Your browser doesn\'t support direct access to the clipboard.': 'お使いのブラウザはクリップボードを使用できません',
	'Copy selection': 'コピー',
	'copy': 'copy',
	'Border radius': '角の丸み',
} as IDictionary<string>;
