export default {
    'Type something': 'Напишите что-либо',
    // About
    'About Jodit': 'О Jodit',
    'Jodit Editor': 'Редактор Jodit',
    'Free Non-commercial Version': 'Версия для не коммерческого использования',
    'Jodit User\'s Guide': 'Jodit Руководство пользователя',
    'contains detailed help for using': 'содержит детальную информацию по использованию',
    'For information about the license, please go to our website:': 'Для получения сведений о лицензии , пожалуйста, перейдите на наш сайт:',
    'Buy full version': 'Купить полную версию',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'Авторские права © XDSoft.net - Чупурнов Валерий. Все права защищены.',

    // Toolbar
    'Anchor': 'Анкор',
    'Open in new tab': 'Открывать ссылку в новой вкладке',
    'Open editor in fullsize': 'Открыть редактор в полном размере',
    'Clear Formatting': 'Очистить форматирование',
    'Fill color or set the text color': 'Цвет заливки или цвет текста',
    'Redo': 'Повтор',
    'Undo': 'Отмена',
    'Bold': 'Жирный',
    'Italic': 'Наклонный',
    'Insert Unordered List': 'Вставка маркированного списка',
    'Insert Ordered List': 'Вставить нумерованный список',
    'Justify Center': 'Выровнять по центру',
    'Justify Full': 'Выровнять по ширине',
    'Justify Left': 'Выровнять по левому краю',
    'Justify Right': 'Выровнять по правому краю',
    'Insert Horizontal Line': 'Вставить горизонтальную линию',
    'Insert Image': 'Вставить изображение',
    'Insert link': 'Вставить ссылку',
    'Font size': 'Размер шрифта',
    'Font family': 'Шрифт',

    'Insert format block': 'Вставить блочный элемент',
    'Normal': 'Нормальный текст',
    'Heading 1': 'Заголовок 1',
    'Heading 2': 'Заголовок 2',
    'Heading 3': 'Заголовок 3',
    'Heading 4': 'Заголовок 4',
    'Quote': 'Цитата',
    'Code': 'Код',

    'Insert': 'Вставить',
    'Insert table': 'Вставить таблицу',
    'Change mode': 'Источник',

    //plugin Image
    'Margins': 'Отступы',
    'top': 'сверху',
    'right': 'справа',
    'bottom': 'снизу',
    'left': 'слева',
    'Styles': 'Стили',
    'Classes': 'Классы',
    'Align': 'Выравнивание',
    'Right': 'По правому краю',
    'Center': 'По центру',
    'Left': 'По левому краю',
    '--Not Set--': '--не устанавливать--',
    'Src': 'src',
    'Title': 'Заголовок',
    'Alternative': 'Альтернативный текст (alt)',
    'Link': 'Ссылка',
    'Open link in new tab': 'Открывать ссылку в новом окне',
    'Image': 'Изображение',
    'Advansed': 'Расширенные',
    'Image properties': 'Свойства изображения',
    'Cancel': 'Отмена',
    'Ok': 'Ok',

    //plugin insertHTML
    'Your code is similar to HTML. Paste as HTML?': 'Ваш текст, который вы пытаетесь вставить похож на HTML. Вставить его как HTML?',
    'Paste as HTML': 'Вставить как HTML?',

    // File Browser module
    'File Browser': 'Браузер файлов',
    'Error on load list': 'Ошибка при загрузке списка изображений',
    'Error on load folders': 'Ошибка при загрузке списка директорий',
    'Are you shure?': 'Вы уверены?',
    'Enter Directory name': 'Введите название директории',
    'Create directory': 'Создать директорию',
    'type name': 'введите название',

    // Form module
    'Drop image': 'Перетащите сюда изображение',
    'or click': 'или нажмите',
    'Alternative text': 'Альтернативный текст',
    'Browse': 'Сервер',
    'Upload': 'Загрузка',

    'Background': 'Фон',
    'Text': 'Текст',

     // popap module
    'Top': ' К верху',
    'Middle': 'По середине',
    'Bottom': 'К низу',
    'Insert column before': 'Вставить столбец до',
    'Insert column after': 'Вставить столбец после',
    'Insert row above': 'Вставить ряд выше',
    'Insert row below': 'Вставить ряд ниже',
    'Delete table': 'Удалить таблицу',
    'Delete row': 'Удалять ряд',
    'Delete column': 'Удалить столбец',
    'Empty cell': 'Отчистить ячейку'
};