/*!
 * Jodit Editor (https://xdsoft.net/jodit/)
 * Released under MIT see LICENSE.txt in the project root for license information.
 * Copyright (c) 2013-2026 Valerii Chupurnov. All rights reserved. https://xdsoft.net
 */

// Slovak (Slovenčina)

module.exports = {
	'Type something': 'Napíšte niečo',
	'About Jodit': 'O editore Jodit',
	'Jodit Editor': 'Editor Jodit',
	'Free Non-commercial Version': 'Bezplatná verzia na nekomerčné použitie',
	"Jodit User's Guide": 'Používateľská príručka Jodit',
	'contains detailed help for using': 'obsahuje podrobnú pomoc s používaním',
	'For information about the license, please go to our website:':
		'Informácie o licencii nájdete na našej webovej stránke:',
	'Buy full version': 'Kúpiť plnú verziu',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Copyright © XDSoft.net - Chupurnov Valeriy. Všetky práva vyhradené.',
	Anchor: 'Kotva',
	'Open in new tab': 'Otvoriť na novej karte',
	'Open in fullsize': 'Otvoriť na celú obrazovku',
	'Clear Formatting': 'Vymazať formátovanie',
	'Fill color or set the text color': 'Farba výplne alebo textu',
	Redo: 'Znova',
	Undo: 'Späť',
	Bold: 'Tučné písmo',
	Italic: 'Kurzíva',
	'Insert Unordered List': 'Vložiť zoznam s odrážkami',
	'Insert Ordered List': 'Vložiť číslovaný zoznam',
	'Align Center': 'Zarovnať na stred',
	'Align Justify': 'Zarovnať do bloku',
	'Align Left': 'Zarovnať doľava',
	'Align Right': 'Zarovnať doprava',
	'Insert Horizontal Line': 'Vložiť vodorovnú čiaru',
	'Insert Image': 'Vložiť obrázok',
	'Insert file': 'Vložiť súbor',
	'Insert youtube/vimeo video': 'Vložiť video YouTube/Vimeo',
	'Insert link': 'Vložiť odkaz',
	'Font size': 'Veľkosť písma',
	'Font family': 'Typ písma',
	'Insert format block': 'Vložiť formátovaný blok',
	Normal: 'Normálny text',
	'Heading 1': 'Nadpis 1',
	'Heading 2': 'Nadpis 2',
	'Heading 3': 'Nadpis 3',
	'Heading 4': 'Nadpis 4',
	Quote: 'Citácia',
	Code: 'Kód',
	Insert: 'Vložiť',
	'Insert table': 'Vložiť tabuľku',
	'Decrease Indent': 'Zmenšiť odsadenie',
	'Increase Indent': 'Zväčšiť odsadenie',
	'Select Special Character': 'Vybrať špeciálny znak',
	'Insert Special Character': 'Vložiť špeciálny znak',
	'Paint format': 'Kopírovať formát',
	'Change mode': 'Zmeniť režim',
	Margins: 'Okraje',
	top: 'horný',
	right: 'pravý',
	bottom: 'dolný',
	left: 'ľavý',
	Styles: 'Štýly',
	Classes: 'Triedy',
	Align: 'Zarovnanie',
	Right: 'Vpravo',
	Center: 'Na stred',
	Left: 'Vľavo',
	'--Not Set--': '--nenastavené--',
	Src: 'Zdroj',
	Title: 'Názov',
	Alternative: 'Alternatívny text (alt)',
	Link: 'Odkaz',
	'Open link in new tab': 'Otvoriť odkaz na novej karte',
	Image: 'Obrázok',
	file: 'súbor',
	Advanced: 'Rozšírené',
	'Image properties': 'Vlastnosti obrázka',
	Cancel: 'Zrušiť',
	Ok: 'OK',
	'Your code is similar to HTML. Keep as HTML?':
		'Váš kód sa podobá na HTML. Ponechať ho ako HTML?',
	'Paste as HTML': 'Vložiť ako HTML',
	Keep: 'Ponechať',
	Clean: 'Vyčistiť',
	'Insert as Text': 'Vložiť ako text',
	'Insert only Text': 'Vložiť iba text',
	'Word Paste Detected': 'Zistil sa obsah z Wordu alebo Excelu',
	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'Vložený obsah pochádza z dokumentu Microsoft Word/Excel. Chcete zachovať formátovanie alebo ho vyčistiť?',
	'File Browser': 'Prehliadač súborov',
	'Error on load list': 'Chyba pri načítaní zoznamu súborov',
	'Error on load folders': 'Chyba pri načítaní priečinkov',
	'Are you sure?': 'Ste si istí?',
	'Enter Directory name': 'Zadajte názov priečinka',
	'Create directory': 'Vytvoriť priečinok',
	'type name': 'zadajte názov',
	'Drop image': 'Presuňte sem obrázok',
	'Drop file': 'Presuňte sem súbor',
	'or click': 'alebo kliknite',
	'Alternative text': 'Alternatívny text',
	Browse: 'Prehľadávať',
	Upload: 'Nahrať',
	Background: 'Pozadie',
	Text: 'Text',
	Top: 'Hore',
	Middle: 'Na stred',
	Bottom: 'Dole',
	'Insert column before': 'Vložiť stĺpec pred',
	'Insert column after': 'Vložiť stĺpec za',
	'Insert row above': 'Vložiť riadok nad',
	'Insert row below': 'Vložiť riadok pod',
	'Delete table': 'Odstrániť tabuľku',
	'Delete row': 'Odstrániť riadok',
	'Delete column': 'Odstrániť stĺpec',
	'Empty cell': 'Vyprázdniť bunku',
	source: 'HTML',
	bold: 'tučné písmo',
	italic: 'kurzíva',
	brush: 'štetec',
	link: 'odkaz',
	undo: 'späť',
	redo: 'znova',
	table: 'tabuľka',
	image: 'obrázok',
	eraser: 'guma',
	paragraph: 'odstavec',
	fontsize: 'veľkosť písma',
	video: 'video',
	font: 'písmo',
	about: 'o editore',
	print: 'tlačiť',
	underline: 'podčiarknuté',
	strikethrough: 'prečiarknuté',
	indent: 'zväčšiť odsadenie',
	outdent: 'zmenšiť odsadenie',
	fullsize: 'režim celej obrazovky',
	shrink: 'zmenšiť',
	hr: 'vodorovná čiara',
	ul: 'zoznam s odrážkami',
	ol: 'číslovaný zoznam',
	cut: 'vystrihnúť',
	selectall: 'vybrať všetko',
	'Embed code': 'Vložiť kód',
	'Open link': 'Otvoriť odkaz',
	'Edit link': 'Upraviť odkaz',
	'No follow': 'Atribút nofollow',
	Unlink: 'Odstrániť odkaz',
	Eye: 'Zobraziť',
	pencil: 'Upraviť',
	Update: 'Aktualizovať',
	' URL': 'URL',
	Edit: 'Upraviť',
	'Horizontal align': 'Vodorovné zarovnanie',
	Filter: 'Filter',
	'Sort by changed': 'Zoradiť podľa poslednej zmeny',
	'Sort by name': 'Zoradiť podľa názvu',
	'Sort by size': 'Zoradiť podľa veľkosti',
	'Add folder': 'Pridať priečinok',
	Reset: 'Obnoviť',
	Save: 'Uložiť',
	'Save as ...': 'Uložiť ako…',
	Resize: 'Zmeniť veľkosť',
	Crop: 'Orezať',
	Width: 'Šírka',
	Height: 'Výška',
	'Keep Aspect Ratio': 'Zachovať pomer strán',
	Yes: 'Áno',
	No: 'Nie',
	Remove: 'Odstrániť',
	Select: 'Vybrať',
	'Chars: %d': 'Znaky: %d',
	'Words: %d': 'Slová: %d',
	All: 'Všetko',
	'Select %s': 'Vybrať %s',
	'Select all': 'Vybrať všetko',
	'Vertical align': 'Zvislé zarovnanie',
	Split: 'Rozdeliť',
	'Split vertical': 'Rozdeliť zvislo',
	'Split horizontal': 'Rozdeliť vodorovne',
	Merge: 'Zlúčiť',
	'Add column': 'Pridať stĺpec',
	'Add row': 'Pridať riadok',
	Delete: 'Odstrániť',
	Border: 'Okraj',
	'License: %s': 'Licencia: %s',
	'Strike through': 'Prečiarknuté',
	Underline: 'Podčiarknuté',
	superscript: 'Horný index',
	subscript: 'Dolný index',
	'Cut selection': 'Vystrihnúť výber',
	Break: 'Zalomenie',
	'Search for': 'Hľadať',
	'Replace with': 'Nahradiť čím',
	Replace: 'Nahradiť',
	Paste: 'Vložiť',
	'Choose Content to Paste': 'Vyberte obsah na vloženie',
	'You can only edit your own images. Download this image on the host?':
		'Môžete upravovať iba vlastné obrázky. Stiahnuť tento obrázok na server?',
	'The image has been successfully uploaded to the host!':
		'Obrázok bol úspešne nahraný na server!',
	palette: 'paleta',
	'There are no files': 'V tomto priečinku nie sú žiadne súbory.',
	Rename: 'Premenovať',
	'Enter new name': 'Zadajte nový názov',
	preview: 'Ukážka',
	download: 'Stiahnuť',
	'Paste from clipboard': 'Vložiť zo schránky',
	"Your browser doesn't support direct access to the clipboard.":
		'Váš prehliadač nepodporuje priamy prístup do schránky.',
	'Copy selection': 'Kopírovať výber',
	copy: 'kopírovať',
	'Border radius': 'Zaoblenie rohov',
	'Show all': 'Zobraziť všetko',
	Apply: 'Použiť',
	'Please fill out this field': 'Vyplňte toto pole',
	'Please enter a web address': 'Zadajte webovú adresu',
	Default: 'Predvolené',
	Circle: 'Kruh',
	Dot: 'Bodka',
	Quadrate: 'Štvorec',
	Find: 'Nájsť',
	'Find Previous': 'Nájsť predchádzajúce',
	'Find Next': 'Nájsť nasledujúce',
	'Insert className': 'Vložte názov triedy',
	'Press Alt for custom resizing': 'Stlačte Alt na vlastnú zmenu veľkosti',
	'Upload file': 'Nahrať súbor',
	'Remove file': 'Odstrániť súbor',
	'Update file list': 'Aktualizovať zoznam súborov',
	'Select file': 'Vybrať súbor',
	'Edit image': 'Upraviť obrázok',
	'Tiles view': 'Zobrazenie dlaždíc',
	'List view': 'Zobrazenie zoznamu'
};
