/*!
 * Jodit Editor (https://xdsoft.net/jodit/)
 * Released under MIT see LICENSE.txt in the project root for license information.
 * Copyright (c) 2013-2025 Valeriy Chupurnov. All rights reserved. https://xdsoft.net
 */

module.exports = {
	'Type something': 'Skriv något...',
	'About Jodit': 'Om Jodit',
	'Jodit Editor': 'Jodit Editor',
	"Jodit User's Guide": 'Jodit användarguide',
	'contains detailed help for using':
		'Innehåller detaljerad hjälp för användning',
	'For information about the license, please go to our website:':
		'För information om licensen, vänligen besök vår webbsida:',
	'Buy full version': 'Köp full version',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Upphovsrätt © XDSoft.net - Chupurnov Valeriy. Alla rättigheter förbehållna.',
	Anchor: 'Ankare',
	'Open in new tab': 'Öppna i ny flik',
	'Open in fullsize': 'Öppna i fullskärm',
	'Clear Formatting': 'Rensa formatering',
	'Fill color or set the text color': 'Fyll färg eller ställ in textfärg',
	Redo: 'Gör om',
	Undo: 'Ångra',
	Bold: 'Fetstil',
	Italic: 'Kursiv',
	'Insert Unordered List': 'Infoga punktlista',
	'Insert Ordered List': 'Infoga numrerad lista',
	'Align Center': 'Centrera',
	'Align Justify': 'Justera',
	'Align Left': 'Vänsterjustera',
	'Align Right': 'Högerjustera',
	'Insert Horizontal Line': 'Infoga horisontell linje',
	'Insert Image': 'Infoga bild',
	'Insert file': 'Infoga fil',
	'Insert youtube/vimeo video': 'Infoga YouTube/Vimeo-video',
	'Insert link': 'Infoga länk',
	'Font size': 'Teckenstorlek',
	'Font family': 'Teckensnitt',
	'Insert format block': 'Infoga formateringsblock',
	Normal: 'Normal',
	'Heading 1': 'Rubrik 1',
	'Heading 2': 'Rubrik 2',
	'Heading 3': 'Rubrik 3',
	'Heading 4': 'Rubrik 4',
	Quote: 'Citat',
	Code: 'Kod',
	Insert: 'Infoga',
	'Insert table': 'Infoga tabell',
	'Decrease Indent': 'Minska indrag',
	'Increase Indent': 'Öka indrag',
	'Select Special Character': 'Välj specialtecken',
	'Insert Special Character': 'Infoga specialtecken',
	'Paint format': 'Kopiera format',
	'Change mode': 'Byt läge (WYSIWYG/HTML)',
	Margins: 'Marginaler',
	top: 'överst',
	right: 'höger',
	bottom: 'nederst',
	left: 'vänster',
	Styles: 'Stilar',
	Classes: 'Klasser',
	Align: 'Justering',
	Right: 'Höger',
	Center: 'Centrera',
	Left: 'Vänster',
	'--Not Set--': '--Inte inställd--',
	Src: 'Källa',
	Title: 'Titel',
	Alternative: 'Alternativ',
	Filter: 'Filter',
	Link: 'Länk',
	'Open link in new tab': 'Öppna länk i ny flik',
	Image: 'Bild',
	file: 'fil',
	Advanced: 'Avancerad',
	'Image properties': 'Bildegenskaper',
	Cancel: 'Avbryt',
	Ok: 'OK',
	'Your code is similar to HTML. Keep as HTML?':
		'Din kod liknar HTML. Vill du behålla som HTML?',
	'Paste as HTML': 'Klistra in som HTML',
	Keep: 'Behåll',
	Clean: 'Rensa',
	'Insert as Text': 'Klistra in som text',
	'Word Paste Detected': 'Word-klistring upptäckt',
	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'Det inklistrade innehållet kommer från ett Microsoft Word/Excel-dokument. Vill du behålla formatet eller rensa det?',
	'Insert only Text': 'Klistra in endast text',
	'File Browser': 'Filutforskare',
	'Error on load list': 'Fel vid inläsning av lista',
	'Error on load folders': 'Fel vid inläsning av mappar',
	'Are you sure?': 'Är du säker?',
	'Enter Directory name': 'Ange mappnamn',
	'Create directory': 'Skapa mapp',
	'type name': 'skriv namn',
	'Drop image': 'Släpp bild',
	'Drop file': 'Släpp fil',
	'or click': 'eller klicka',
	'Alternative text': 'Alternativ text',
	Browse: 'Bläddra',
	Upload: 'Ladda upp',
	Background: 'Bakgrund',
	Border: 'Kantlinje',
	Text: 'Text',
	Top: 'Topp',
	Middle: 'Mitten',
	Bottom: 'Botten',
	'Insert column before': 'Infoga kolumn före',
	'Insert column after': 'Infoga kolumn efter',
	'Insert row above': 'Infoga rad ovanför',
	'Insert row below': 'Infoga rad nedanför',
	'Delete table': 'Radera tabell',
	'Delete row': 'Radera rad',
	'Delete column': 'Radera kolumn',
	'Empty cell': 'Töm cell',
	'Chars: %d': 'Tecken: %d',
	'Words: %d': 'Ord: %d',
	Split: 'Dela',
	'Split vertical': 'Dela vertikalt',
	'Split horizontal': 'Dela horisontellt',
	'Strike through': 'Genomstrykning',
	Underline: 'Understrykning',
	superscript: 'Upphöjd skrift',
	subscript: 'Sänkt skrift',
	'Cut selection': 'Klipp ut markering',
	'Select all': 'Välj allt',
	Break: 'Paus',
	'Search for': 'Sök efter',
	'Replace with': 'Ersätt med',
	Replace: 'Ersätt',
	Paste: 'Klistra in',
	'Choose Content to Paste': 'Välj innehåll att klistra in',
	source: 'källa',
	bold: 'fetstil',
	italic: 'kursiv',
	brush: 'pensel',
	link: 'länk',
	undo: 'ångra',
	redo: 'gör om',
	table: 'tabell',
	image: 'bild',
	eraser: 'radergummi',
	paragraph: 'stycke',
	fontsize: 'teckenstorlek',
	video: 'video',
	font: 'teckensnitt',
	about: 'om redigeringsverktyget',
	print: 'skriv ut',
	underline: 'understrykning',
	strikethrough: 'genomstrykning',
	indent: 'indrag',
	outdent: 'minska indrag',
	fullsize: 'full storlek',
	shrink: 'minska',
	hr: 'linje',
	ul: 'punktlista',
	ol: 'numrerad lista',
	cut: 'klipp ut',
	selectall: 'välj allt',
	'Open link': 'Öppna länk',
	'Edit link': 'Redigera länk',
	'No follow': 'Ingen uppföljning',
	Unlink: 'Ta bort länk',
	Eye: 'Förhandsvisning',
	pencil: 'Redigera',
	' URL': 'URL',
	Reset: 'Återställ',
	Save: 'Spara',
	'Save as ...': 'Spara som ...',
	Resize: 'Ändra storlek',
	Crop: 'Beskär',
	Width: 'Bredd',
	Height: 'Höjd',
	'Keep Aspect Ratio': 'Behåll aspektförhållande',
	Yes: 'Ja',
	No: 'Nej',
	Remove: 'Ta bort',
	Select: 'Välj',
	'Select %s': 'Välj: %s',
	Update: 'Uppdatera',
	'Vertical align': 'Vertikal justering',
	Merge: 'Sammanfoga',
	'Add column': 'Lägg till kolumn',
	'Add row': 'Lägg till rad',
	Delete: 'Radera',
	'Horizontal align': 'Horisontell justering',
	'Sort by changed': 'Sortera efter ändrad',
	'Sort by name': 'Sortera efter namn',
	'Sort by size': 'Sortera efter storlek',
	'Add folder': 'Lägg till mapp',
	palette: 'Palett',
	preview: 'Förhandsvisning',
	'Line height': 'Radavstånd',
	'Insert className': 'Infoga klassnamn',
	apply: 'Tillämpa',
	edit: 'Redigera',
	'Show all': 'Visa alla',
	sound: 'Ljud',
	'Interim Results': 'Preliminära resultat',
	default: 'Standard',
	circle: 'Cirkel',
	dot: 'Prick',
	square: 'Fyrkant',
	'Press Alt for custom resizing':
		'Tryck på Alt för anpassad storleksändring',
	'Copy selection': 'Kopiera markering',
	'Paste from clipboard': 'Klistra in från urklipp',
	Find: 'Hitta'
};
