/*!
 * Jodit Editor (https://xdsoft.net/jodit/)
 * Released under MIT see LICENSE.txt in the project root for license information.
 * Copyright (c) 2013-2023 Valeriy Chupurnov. All rights reserved. https://xdsoft.net
 */

module.exports = {
	'Type something': '輸入一些內容',
	Advanced: '高級',
	'About Jodit': '關於Jodit',
	'Jodit Editor': 'Jodit Editor',
	"Jodit User's Guide": '開發者指南',
	'contains detailed help for using': '使用幫助',
	'For information about the license, please go to our website:':
		'有關許可證的信息，請訪問我們的網站：',
	'Buy full version': '購買完整版本',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.',
	Anchor: 'Anchor',
	'Open in new tab': '在新窗口打開',
	'Open in fullsize': '全屏編輯',
	'Clear Formatting': '清除樣式',
	'Fill color or set the text color': '顏色',
	Redo: '重做',
	Undo: '撤銷',
	Bold: '粗體',
	Italic: '斜體',
	'Insert Unordered List': '符號列表',
	'Insert Ordered List': '編號',
	'Align Center': '居中',
	'Align Justify': '對齊文本',
	'Align Left': '左對齊',
	'Align Right': '右對齊',
	'Insert Horizontal Line': '分割線',
	'Insert Image': '圖片',
	'Insert file': '文件',
	'Insert youtube/vimeo video': 'youtube/vimeo 影片',
	'Insert link': '鏈接',
	'Font size': '字號',
	'Font family': '字體',
	'Insert format block': '格式塊',
	Normal: '文本',
	'Heading 1': '標題1',
	'Heading 2': '標題2',
	'Heading 3': '標題3',
	'Heading 4': '標題4',
	Quote: '引用',
	Code: '代碼',
	Insert: '插入',
	'Insert table': '表格',
	'Decrease Indent': '減少縮進',
	'Increase Indent': '增加縮進',
	'Select Special Character': '選擇特殊符號',
	'Insert Special Character': '特殊符號',
	'Paint format': '格式複製',
	'Change mode': '改變模式',
	Margins: '外邊距（Margins）',
	top: 'top',
	right: 'right',
	bottom: 'bottom',
	left: 'left',
	Styles: '樣式',
	Classes: 'Classes',
	Align: '對齊方式',
	Right: '居右',
	Center: '居中',
	Left: '居左',
	'--Not Set--': '無',
	Src: 'Src',
	Title: 'Title',
	Alternative: '替代',
	Link: 'Link',
	'Open link in new tab': '在新窗口打開鏈接',
	Image: '圖片',
	file: 'file',
	'Image properties': '圖片屬性',
	Cancel: '取消',
	Ok: '確定',
	'Your code is similar to HTML. Keep as HTML?':
		'你黏貼的文本是一段html代碼，是否保留源格式',
	'Paste as HTML': 'html黏貼',
	Keep: '保留源格式',
	Clean: '匹配目標格式',
	'Insert as Text': '把html代碼視為普通文本',
	'Word Paste Detected': '文本黏貼',
	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'正在黏貼 Word/Excel 的文本，是否保留源格式？',
	'Insert only Text': '只保留文本',
	'File Browser': '文件管理',
	'Error on load list': '加載list錯誤',
	'Error on load folders': '加載folders錯誤',
	'Are you sure?': '你確定嗎？',
	'Enter Directory name': '輸入路徑',
	'Create directory': '創建路徑',
	'type name': 'type name',
	'Drop image': '拖動圖片到此',
	'Drop file': '拖動文件到此',
	'or click': '或點擊',
	'Alternative text': '替代文字',
	Browse: '瀏覽',
	Upload: '上傳',
	Background: '背景色',
	Text: '文字',
	Top: '頂部',
	Middle: '中間',
	Bottom: '底部',
	'Insert column before': '在之前插入列',
	'Insert column after': '在之後插入列',
	'Insert row above': '在之前插入行',
	'Insert row below': '在之後插入行',
	'Delete table': '刪除表格',
	'Delete row': '刪除行',
	'Delete column': '刪除列',
	'Empty cell': '清除內容',
	'Chars: %d': '字符數: %d',
	'Words: %d': '單詞數: %d',
	'Strike through': '刪除線',
	Underline: '下劃線',
	superscript: '上標',
	subscript: '下標',
	'Cut selection': '剪切',
	'Select all': '全選',
	Break: 'Pause',
	'Search for': '查找',
	'Replace with': '替換為',
	Replace: 'แทนที่',
	Paste: '黏貼',
	'Choose Content to Paste': '選擇內容並黏貼',
	All: '全部',
	source: '源碼',
	bold: '粗體',
	italic: '斜體',
	brush: '顏色',
	link: '鏈接',
	undo: '撤銷',
	redo: '重做',
	table: '表格',
	image: '圖片',
	eraser: '橡皮擦',
	paragraph: '段落',
	fontsize: '字號',
	video: '影片',
	font: '字體',
	about: '關於',
	print: '打印',
	underline: '下劃線',
	strikethrough: '上出現',
	indent: '增加縮進',
	outdent: '減少縮進',
	fullsize: '全屏',
	shrink: '收縮',
	hr: '分割線',
	ul: '無序列表',
	ol: '順序列表',
	cut: '剪切',
	selectall: '全選',
	'Open link': '打開鏈接',
	'Edit link': '編輯鏈接',
	'No follow': 'No follow',
	Unlink: '取消連結',
	Eye: '回顧',
	' URL': 'URL',
	Reset: '重置',
	Save: '保存',
	'Save as ...': '保存為',
	Resize: '調整大小',
	Crop: 'Crop',
	Width: '寬',
	Height: '高',
	'Keep Aspect Ratio': '保存長寬比',
	Yes: '是',
	No: '不',
	Remove: '移除',
	Select: '選擇',
	'Select %s': '選擇: %s',
	Update: '更新',
	'Vertical align': '垂直對齊',
	Merge: '合併',
	'Add column': '添加列',
	'Add row': '添加行',
	Border: '邊框',
	'Embed code': '嵌入代碼',
	Delete: '刪除',
	'Horizontal align': '水平對齊',
	Filter: '篩選',
	'Sort by changed': '修改時間排序',
	'Sort by name': '名稱排序',
	'Sort by size': '大小排序',
	'Add folder': '新建文件夾',
	Split: '拆分',
	'Split vertical': '垂直拆分',
	'Split horizontal': '水平拆分',
	'You can only edit your own images. Download this image on the host?':
		'你只能編輯你自己的圖片。是否下載此圖片到本地?',
	'The image has been successfully uploaded to the host!': '圖片上傳成功',
	palette: '調色板',
	pencil: '鉛筆',
	'There are no files': '此目錄中沒有文件。',
	Rename: '重命名',
	'Enter new name': '輸入新名稱',
	preview: '預覽',
	download: '下載',
	'Paste from clipboard': '從剪貼板貼上',
	"Your browser doesn't support direct access to the clipboard.":
		'瀏覽器無法存取剪贴板。',
	'Copy selection': '複製已選取項目',
	copy: '複製',
	'Border radius': '邊框圓角',
	'Show all': '顯示所有',
	Apply: '應用',
	'Please fill out this field': 'ได้โปรดกรอกช่องข้อมูลนี้',
	'Please enter a web address': 'โปรดเติมที่อยู่บนเว็บ',
	Default: 'ค่าปริยาย',
	Circle: 'วงกลม',
	Dot: 'จุด',
	Quadrate: 'Quadrate',
	Find: 'ค้นหา',
	'Find Previous': 'ค้นหาก่อนหน้านี้',
	'Find Next': 'ค้นหาถัดไป',
	'Insert className': 'ใส่ชื่อคลาส',
	'Press Alt for custom resizing': 'กดอัลท์สำหรับการปรับขนาดที่กำหนดเอง'
};
