declare const _default: {
    'Type something': string;
    'About Jodit': string;
    'Jodit Editor': string;
    'Free Non-commercial Version': string;
    'GNU General Public License, version 2 or later': string;
    'Jodit User\'s Guide': string;
    'contains detailed help for using': string;
    'For information about the license, please go to our website:': string;
    'Buy full version': string;
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': string;
    'Anchor': string;
    'Open in new tab': string;
    'Open editor in fullsize': string;
    'Clear Formatting': string;
    'Fill color or set the text color': string;
    'Redo': string;
    'Undo': string;
    'Bold': string;
    'Italic': string;
    'Insert Unordered List': string;
    'Insert Ordered List': string;
    'Align Center': string;
    'Align Justify': string;
    'Align Left': string;
    'Align Right': string;
    'Insert Horizontal Line': string;
    'Insert Image': string;
    'Insert file': string;
    'Insert youtube/vimeo video': string;
    'Insert link': string;
    'Font size': string;
    'Font family': string;
    'Insert format block': string;
    'Normal': string;
    'Heading 1': string;
    'Heading 2': string;
    'Heading 3': string;
    'Heading 4': string;
    'Quote': string;
    'Code': string;
    'Insert': string;
    'Insert table': string;
    'Decrease Indent': string;
    'Increase Indent': string;
    'Select Special Character': string;
    'Insert Special Character': string;
    'Paint format': string;
    'Change mode': string;
    'Margins': string;
    'top': string;
    'right': string;
    'bottom': string;
    'left': string;
    'Styles': string;
    'Classes': string;
    'Align': string;
    'Right': string;
    'Center': string;
    'Left': string;
    '--Not Set--': string;
    'Src': string;
    'Title': string;
    'Alternative': string;
    'Link': string;
    'Open link in new tab': string;
    'Image': string;
    'file': string;
    'Advanced': string;
    'Image properties': string;
    'Cancel': string;
    'Ok': string;
    'Your code is similar to HTML. Keep as HTML?': string;
    'Paste as HTML': string;
    'Keep': string;
    'Clean': string;
    'Insert as Text': string;
    'Insert only Text': string;
    'Word Paste Detected': string;
    'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?': string;
    'File Browser': string;
    'Error on load list': string;
    'Error on load folders': string;
    'Are you sure?': string;
    'Enter Directory name': string;
    'Create directory': string;
    'type name': string;
    'Drop image': string;
    'Drop file': string;
    'or click': string;
    'Alternative text': string;
    'Browse': string;
    'Upload': string;
    'Background': string;
    'Text': string;
    'Top': string;
    'Middle': string;
    'Bottom': string;
    'Insert column before': string;
    'Insert column after': string;
    'Insert row above': string;
    'Insert row below': string;
    'Delete table': string;
    'Delete row': string;
    'Delete column': string;
    'Empty cell': string;
    'source': string;
    'bold': string;
    'italic': string;
    'brush': string;
    'link': string;
    'undo': string;
    'redo': string;
    'table': string;
    'image': string;
    'eraser': string;
    'paragraph': string;
    'fontsize': string;
    'video': string;
    'font': string;
    'about': string;
    'print': string;
    'symbol': string;
    'underline': string;
    'strikethrough': string;
    'indent': string;
    'outdent': string;
    'fullsize': string;
    'shrink': string;
    'copyformat': string;
    'hr': string;
    'ul': string;
    'ol': string;
    'cut': string;
    'selectall': string;
    'Embed code': string;
    'Open link': string;
    'Edit link': string;
    'No follow': string;
    'Unlink': string;
    'Update': string;
    ' URL': string;
    'Edit': string;
    'Horizontal align': string;
    'Filter': string;
    'Sort by changed': string;
    'Sort by name': string;
    'Sort by size': string;
    'Add folder': string;
    'Reset': string;
    'Save': string;
    'Save as ...': string;
    'Resize': string;
    'Crop': string;
    'Width': string;
    'Height': string;
    'Keep Aspect Ratio': string;
    'Yes': string;
    'No': string;
    'Remove': string;
    'Select': string;
    'Chars: %d': string;
    'Words: %d': string;
    'All': string;
    'Select %s': string;
    'Select all': string;
    'Vertical align': string;
    'Split': string;
    'Split vertical': string;
    'Split horizontal': string;
    'Merge': string;
    'Add column': string;
    'Add row': string;
    'Delete': string;
    'Border': string;
    'License: %s': string;
    'Strike through': string;
    'Underline': string;
    'superscript': string;
    'subscript': string;
    'Cut selection': string;
    'Break': string;
    'Search for': string;
    'Replace with': string;
    'Replace': string;
    'Paste': string;
    'Choose Content to Paste': string;
    'You can only edit your own images. Download this image on the host?': string;
    'The image has been successfully uploaded to the host!': string;
};
export default _default;
