name: GitHub Pages

on:
  push:
    branches:
      - main
    tags-ignore: [ '*' ]

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'New version') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6 #Setup Node
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: make build
      - run: make examples
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./examples

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
