name: GitHub Pages

on:
  push:
    branches:
      - main
    tags-ignore: [ '*' ]

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'New version') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6 #Setup Node
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: make build
      - run: make examples
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./examples

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
