name: Run tests

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'New version') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6 #Setup Node
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Run Karma Tests
      run: |
        npm ci --legacy-peer-deps
        make lint
        make test uglify=true fat=true
